### ISSUE TITLE
resoruces

### ISSUE THREAD

**Issue by alvarolorentedev** [kanekotic/kanekotic-blog#1]
![packman](https://cloud.githubusercontent.com/assets/3071208/15821212/bb8ec23c-2bee-11e6-8560-0724a9c43b04.PNG)

**Comment by kanekotic** [comment]
![npm](https://cloud.githubusercontent.com/assets/3071208/15821342/7f6f3952-2bef-11e6-8345-c904ad96f907.PNG)
